---
- include: base_packages.yml
  tags:
    - packages

- include: hostname.yml
  tags:
    - hostname

- include: timezone.yml
  tags:
    - timezone

- include: selinux.yml
  tags:
    - selinux
  when: (ansible_virtualization_type != 'docker')

- include: users.yml
  tags:
    - users

- include: sudo.yml
  tags:
    - sudo

- include: ssh_conf.yml
  tags:
    - ssh

